from tkinter import*
windo= Tk()
windo.title("Login Page")
show=Label(windo,text="WELCOME  TO KRISHAN  HOSPITAL",font=("Cursive",23),fg="blue")
show.place(x=10,y=25)
windo.geometry("500x400")
id=Label(windo,text="User Id",font=("Courier"))
ent1=Entry(windo)
id.place(x=100,y=120)
ent1.place(x=180,y=120)
pas=Label(windo,text="Password",font=("Courier"))
ent2=Entry(windo)
ent2.config(show="*")
pas.place(x=100,y=150)
ent2.place(x=180,y=150)
btnlogin=Button(windo,text="Login",bg="lightgreen")
btnlogin.place(x=270,y=210)
btnsignup=Button(windo,text="Sign Up",bg="lightgreen")
btnsignup.place(x=180,y=210)
btnexit=Button(windo,text="Exit",bg="lightgreen")
btnexit.place(x=230,y=250)
windo.mainloop()
